### ISSUE TITLE
List of suspicious tile geometries

### ISSUE THREAD

**Issue by JayToDaBee** [JayToDaBee/TwelveAngryNodes_4.24#14]
When running the tool to generate the HexSpotGeometry.json file, some tiles are quite full of error cases. I'll list those here as I find them; note that being listed here does not mean they are incorrect, but that they should at least be checked.

Seems to be something wrong with water height, mostly.

L_0W00W0_XXXIXO_1
L_C000W0_IXXXXO_1
L_C0W0W0_XXXXXI_1
L_CWW0WW_XXXXXX_1
L_CWWW0W_XXXXXX_1 
L_CCCW00_XXXXIX_1
(the last 2 are VERY wrong)

**Comment by scaryrabbit** [comment]
Went over each of them and there was something wrong with each. Some were water height, but issues can also include a vertex not having the right Z value or the pivot point being wrong.

One case worth noting is the the second to last tile that had its pivot off by 0.01, resulting in the land plane being at 0.01 instead of 0 and water being at -2.49

Might be worth making your tool a bit more permissive as this case is probably a precision error by my modeling software, but all others had actual errors on my end that needed correcting.

These should now all be fixed.

**Comment by JayToDaBee** [comment]
I put the acceptable error level in my tool at 0.001. Can change it I guess, but it will probably have effects elsewhere.

**Comment by JayToDaBee** [comment]
Essentially a duplicate of #11, closing.
