### ISSUE TITLE
Fix HexSpotGeometry for cascades

### ISSUE THREAD

**Issue by JayToDaBee** [JayToDaBee/TwelveAngryNodes_4.24#36]
This includes tiles:

L_TR000R_IXOXXX_1
L_TR000R_IXXOXX_1
L_TR000R_IXXXOX_1
L_TR00WR_IXOXXX_1
L_TR00WR_IXXOXX_1
L_TR00WR_IXXXXX_1
L_TR0W0R_IXOXXX_1
L_TR0W0R_IXXXOX_1
L_TR0W0R_IXXXXX_1
L_TR0WWR_IXOXXX_1
L_TR0WWR_IXXXXX_1
L_TRW00R_IXXOXX_1
L_TRW00R_IXXXOX_1
L_TRW00R_IXXXXX_1
L_TRW0WR_IXXOXX_1
L_TRW0WR_IXXXXX_1
L_TRWW0R_IXXXOX_1
L_TRWW0R_IXXXXX_1
L_TRWWWR_IXXXXX_1
L_TTR00R_IXXOXX_1
L_TTR00R_IXXXOX_1
L_TTR00R_XIXOXX_1
L_TTR00R_XIXXOX_1
L_TTR0WR_IXXOXX_1
L_TTR0WR_IXXXXX_1
L_TTR0WR_XIXOXX_1
L_TTR0WR_XIXXXX_1
L_TTRW0R_IXXXOX_1
L_TTRW0R_IXXXXX_1
L_TTRW0R_XIXXOX_1
L_TTRW0R_XIXXXX_1
L_TTRWWR_IXXXXX_1
L_TTRWWR_XIXXXX_1
L_TTTR0R_IXXXOX_1
L_TTTR0R_XIXXOX_1
L_TTTR0R_XXIXOX_1
L_TTTRWR_IXXXXX_1
L_TTTRWR_XIXXXX_1
L_TTTRWR_XXIXXX_1

@scaryrabbit How easy is it for you to give me an image of those tiles with the spots superimposed? I can do without, but would definitely help

**Comment by scaryrabbit** [comment]
Manually drew the bottom of the ramps so that you could see which tile is which.

![L_TR000R_Tiles_1](https://user-images.githubusercontent.com/6887591/108867033-c68a7500-75c2-11eb-8cfe-f50d55a0d0c8.PNG)
![L_TR000R_Tiles_2](https://user-images.githubusercontent.com/6887591/108867037-c7230b80-75c2-11eb-909e-b112418d02e1.PNG)
![L_TR000R_Tiles_3](https://user-images.githubusercontent.com/6887591/108867039-c7230b80-75c2-11eb-8483-57937e85bbd8.PNG)
![L_TTR00R_Tiles_1](https://user-images.githubusercontent.com/6887591/108867040-c7bba200-75c2-11eb-9f56-24d237e1c284.PNG)
![L_TTR00R_Tiles_2](https://user-images.githubusercontent.com/6887591/108867043-c7bba200-75c2-11eb-9f1a-ee34d5b3b092.PNG)
![L_TTTR0R_Tiles_1](https://user-images.githubusercontent.com/6887591/108867045-c8543880-75c2-11eb-84b4-da6ce6741cc3.PNG)

**Comment by JayToDaBee** [comment]
Perfect, this is exactly what I needed!

**Comment by JayToDaBee** [comment]
Done on master in 2f47d081123886ef2654e8abbf7bf7587c2138f6
